Uid: =?us-ascii?q?000000002D981BCA7B16584E89D34CA3742853680700BA72AEFAFEEE06458?=
 =?us-ascii?q?610A5DE8BDDBB9000000000010C0000BA72AEFAFEEE06458610A5DE8BDDBB?=
 =?us-ascii?q?9000001068E1D90000?=
Date: 09/13/2020 06:29:18
DateCreated: 09/13/2020 06:29:18
DateRecieved: 09/13/2020 06:29:19
HtmlBody: <html xmlns:v="urn:schemas-microsoft-com:vml"
 xmlns:o="urn:schemas-microsoft-com:office:office"
 xmlns:w="urn:schemas-microsoft-com:office:word"
 xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
 xmlns="http://www.w3.org/TR/REC-html40"><head><meta name=Generator
 content="Microsoft Word 15 (filtered medium)"><style><!--/* Font Definitions
 */@font-face	{font-family:"Cambria Math";	panose-1:2 4 5 3 5 4 6 3 2
 4;}@font-face	{font-family:Calibri;	panose-1:2 15 5 2 2 2 4 3 2 4;}/* Style
 Definitions */p.MsoNormal, li.MsoNormal, div.MsoNormal	{margin:0in;
	margin-bottom:.0001pt;	font-size:11.0pt;	font-family:"Calibri",sans-serif;
	color:#1F497D;}span.EmailStyle18	{mso-style-type:personal-reply;
	font-family:"Calibri",sans-serif;	color:windowtext;}.MsoChpDefault
	{mso-style-type:export-only;	font-size:10.0pt;}@page WordSection1	{size:8.5in
 11.0in;	margin:1.0in 1.0in 1.0in 1.0in;}div.WordSection1
	{page:WordSection1;}--></style><!--[if gte mso 9]><xml><o:shapedefaults
 v:ext="edit" spidmax="1026" /></xml><![endif]--><!--[if gte mso
 9]><xml><o:shapelayout v:ext="edit"><o:idmap v:ext="edit" data="1"
 /></o:shapelayout></xml><![endif]--></head><body lang=EN-US link="#0563C1"
 vlink="#954F72"><div class=WordSection1><p class=MsoNormal><span
 style='color:windowtext'>Approved<o:p></o:p></span></p><p
 class=MsoNormal><span
 style='color:windowtext'><o:p>&nbsp;</o:p></span></p><div><div
 style='border:none;border-top:solid #E1E1E1 1.0pt;padding:3.0pt 0in 0in
 0in'><p class=MsoNormal><b><span
 style='color:windowtext'>From:</span></b><span style='color:windowtext'> Alok
 Priyadarshi &lt;apriyadarshi@enphaseenergy.com&gt; <br><b>Sent:</b> Saturday,
 September 12, 2020 3:53 AM<br><b>To:</b> Alok Priyadarshi
 &lt;apriyadarshi@enphaseenergy.com&gt;<br><b>Subject:</b> Invoice no:- 307002
 PO No:- 2026425 Needs Approval<o:p></o:p></span></p></div></div><p
 class=MsoNormal><o:p>&nbsp;</o:p></p><p class=MsoNormal
 style='margin-bottom:12.0pt'>Hi, <br><br>Please review the attached invoice
 and provide your email approval for processing if such services have been
 received against this invoice. <br><br>Also, kindly share by email the PO
 number to match the invoice to. The AP team is unable to pay the vendor
 without matching to a PO in Oracle. <br>Invoice details:<o:p></o:p></p><table
 class=MsoNormalTable border=1 cellspacing=0 cellpadding=0 width=450
 style='width:337.5pt;margin-left:37.5pt'><tr><td
 style='background:lightblue;padding:.75pt .75pt .75pt .75pt'><p
 class=MsoNormal align=center style='text-align:center'><b>Invoice
 Date<o:p></o:p></b></p></td><td style='background:lightblue;padding:.75pt
 .75pt .75pt .75pt'><p class=MsoNormal align=center
 style='text-align:center'><b>Invoice Number<o:p></o:p></b></p></td><td
 style='background:lightblue;padding:.75pt .75pt .75pt .75pt'><p
 class=MsoNormal align=center
 style='text-align:center'><b>Vendor<o:p></o:p></b></p></td><td
 style='background:lightblue;padding:.75pt .75pt .75pt .75pt'><p
 class=MsoNormal align=center
 style='text-align:center'><b>Amount<o:p></o:p></b></p></td><td
 style='background:lightblue;padding:.75pt .75pt .75pt .75pt'><p
 class=MsoNormal align=center style='text-align:center'><b>PO
 Number<o:p></o:p></b></p></td></tr><tr><td style='padding:.75pt .75pt .75pt
 .75pt'><p class=MsoNormal>08/05/2020 00:00:00<o:p></o:p></p></td><td
 style='padding:.75pt .75pt .75pt .75pt'><p
 class=MsoNormal>307002<o:p></o:p></p></td><td style='padding:.75pt .75pt
 .75pt .75pt'><p class=MsoNormal>CLEARPATH WORKFORCE
 MANAGEMENT<o:p></o:p></p></td><td style='padding:.75pt .75pt .75pt .75pt'><p
 class=MsoNormal>1591.65<o:p></o:p></p></td><td style='padding:.75pt .75pt
 .75pt .75pt'><p class=MsoNormal>2026425<o:p></o:p></p></td></tr></table><p
 class=MsoNormal><br><br>Regards,<br>AP Team
 <o:p></o:p></p></div></body></html>
PlainText: Approved From: Alok Priyadarshi <apriyadarshi@enphaseenergy.com>
 Sent: Saturday, September 12, 2020 3:53 AMTo: Alok Priyadarshi
 <apriyadarshi@enphaseenergy.com>Subject: Invoice no:- 307002 PO No:- 2026425
 Needs Approval Hi, Please review the attached invoice and provide your email
 approval for processing if such services have been received against this
 invoice. Also, kindly share by email the PO number to match the invoice to.
 The AP team is unable to pay the vendor without matching to a PO in Oracle.
 Invoice details:Invoice DateInvoice NumberVendorAmountPO Number08/05/2020
 00:00:00307002CLEARPATH WORKFORCE MANAGEMENT1591.652026425Regards,AP Team
Size: 40858
Sender: Alok Priyadarshi <apriyadarshi@enphaseenergy.com>
From: Alok Priyadarshi <apriyadarshi@enphaseenergy.com>
To: Alok Priyadarshi <apriyadarshi@enphaseenergy.com>
Subject: RE: Invoice no:- 307002  PO No:- 2026425   Needs Approval
MIME-Version: 1.0
Content-Type: multipart/alternative; boundary="=-0bwXtqomHyVrDAYGM2Zttg=="

--=-0bwXtqomHyVrDAYGM2Zttg==
Content-Type: text/plain; charset=us-ascii

Approved

 

From: Alok Priyadarshi <apriyadarshi@enphaseenergy.com> 
Sent: Saturday, September 12, 2020 3:53 AM
To: Alok Priyadarshi <apriyadarshi@enphaseenergy.com>
Subject: Invoice no:- 307002 PO No:- 2026425 Needs Approval

 

Hi, 

Please review the attached invoice and provide your email approval for processing if such services have been received against this invoice. 

Also, kindly share by email the PO number to match the invoice to. The AP team is unable to pay the vendor without matching to a PO in Oracle. 
Invoice details:

Invoice Date

Invoice Number

Vendor

Amount

PO Number

08/05/2020 00:00:00

307002

CLEARPATH WORKFORCE MANAGEMENT

1591.65

2026425



Regards,
AP Team 

--=-0bwXtqomHyVrDAYGM2Zttg==
Content-Type: text/html
Content-Transfer-Encoding: base64
Content-Id: <731ec694-8595-4956-9eae-2fe675bc95d8>

PGh0bWwgeG1sbnM6dj0idXJuOnNjaGVtYXMtbWljcm9zb2Z0LWNvbTp2bWwiIHhtbG5zOm89
InVybjpzY2hlbWFzLW1pY3Jvc29mdC1jb206b2ZmaWNlOm9mZmljZSIgeG1sbnM6dz0idXJu
OnNjaGVtYXMtbWljcm9zb2Z0LWNvbTpvZmZpY2U6d29yZCIgeG1sbnM6bT0iaHR0cDovL3Nj
aGVtYXMubWljcm9zb2Z0LmNvbS9vZmZpY2UvMjAwNC8xMi9vbW1sIiB4bWxucz0iaHR0cDov
L3d3dy53My5vcmcvVFIvUkVDLWh0bWw0MCI+PGhlYWQ+PG1ldGEgbmFtZT1HZW5lcmF0b3Ig
Y29udGVudD0iTWljcm9zb2Z0IFdvcmQgMTUgKGZpbHRlcmVkIG1lZGl1bSkiPjxzdHlsZT48
IS0tDQovKiBGb250IERlZmluaXRpb25zICovDQpAZm9udC1mYWNlDQoJe2ZvbnQtZmFtaWx5
OiJDYW1icmlhIE1hdGgiOw0KCXBhbm9zZS0xOjIgNCA1IDMgNSA0IDYgMyAyIDQ7fQ0KQGZv
bnQtZmFjZQ0KCXtmb250LWZhbWlseTpDYWxpYnJpOw0KCXBhbm9zZS0xOjIgMTUgNSAyIDIg
MiA0IDMgMiA0O30NCi8qIFN0eWxlIERlZmluaXRpb25zICovDQpwLk1zb05vcm1hbCwgbGku
TXNvTm9ybWFsLCBkaXYuTXNvTm9ybWFsDQoJe21hcmdpbjowaW47DQoJbWFyZ2luLWJvdHRv
bTouMDAwMXB0Ow0KCWZvbnQtc2l6ZToxMS4wcHQ7DQoJZm9udC1mYW1pbHk6IkNhbGlicmki
LHNhbnMtc2VyaWY7DQoJY29sb3I6IzFGNDk3RDt9DQpzcGFuLkVtYWlsU3R5bGUxOA0KCXtt
c28tc3R5bGUtdHlwZTpwZXJzb25hbC1yZXBseTsNCglmb250LWZhbWlseToiQ2FsaWJyaSIs
c2Fucy1zZXJpZjsNCgljb2xvcjp3aW5kb3d0ZXh0O30NCi5Nc29DaHBEZWZhdWx0DQoJe21z
by1zdHlsZS10eXBlOmV4cG9ydC1vbmx5Ow0KCWZvbnQtc2l6ZToxMC4wcHQ7fQ0KQHBhZ2Ug
V29yZFNlY3Rpb24xDQoJe3NpemU6OC41aW4gMTEuMGluOw0KCW1hcmdpbjoxLjBpbiAxLjBp
biAxLjBpbiAxLjBpbjt9DQpkaXYuV29yZFNlY3Rpb24xDQoJe3BhZ2U6V29yZFNlY3Rpb24x
O30NCi0tPjwvc3R5bGU+PCEtLVtpZiBndGUgbXNvIDldPjx4bWw+DQo8bzpzaGFwZWRlZmF1
bHRzIHY6ZXh0PSJlZGl0IiBzcGlkbWF4PSIxMDI2IiAvPg0KPC94bWw+PCFbZW5kaWZdLS0+
PCEtLVtpZiBndGUgbXNvIDldPjx4bWw+DQo8bzpzaGFwZWxheW91dCB2OmV4dD0iZWRpdCI+
DQo8bzppZG1hcCB2OmV4dD0iZWRpdCIgZGF0YT0iMSIgLz4NCjwvbzpzaGFwZWxheW91dD48
L3htbD48IVtlbmRpZl0tLT48L2hlYWQ+PGJvZHkgbGFuZz1FTi1VUyBsaW5rPSIjMDU2M0Mx
IiB2bGluaz0iIzk1NEY3MiI+PGRpdiBjbGFzcz1Xb3JkU2VjdGlvbjE+PHAgY2xhc3M9TXNv
Tm9ybWFsPjxzcGFuIHN0eWxlPSdjb2xvcjp3aW5kb3d0ZXh0Jz5BcHByb3ZlZDxvOnA+PC9v
OnA+PC9zcGFuPjwvcD48cCBjbGFzcz1Nc29Ob3JtYWw+PHNwYW4gc3R5bGU9J2NvbG9yOndp
bmRvd3RleHQnPjxvOnA+Jm5ic3A7PC9vOnA+PC9zcGFuPjwvcD48ZGl2PjxkaXYgc3R5bGU9
J2JvcmRlcjpub25lO2JvcmRlci10b3A6c29saWQgI0UxRTFFMSAxLjBwdDtwYWRkaW5nOjMu
MHB0IDBpbiAwaW4gMGluJz48cCBjbGFzcz1Nc29Ob3JtYWw+PGI+PHNwYW4gc3R5bGU9J2Nv
bG9yOndpbmRvd3RleHQnPkZyb206PC9zcGFuPjwvYj48c3BhbiBzdHlsZT0nY29sb3I6d2lu
ZG93dGV4dCc+IEFsb2sgUHJpeWFkYXJzaGkgJmx0O2Fwcml5YWRhcnNoaUBlbnBoYXNlZW5l
cmd5LmNvbSZndDsgPGJyPjxiPlNlbnQ6PC9iPiBTYXR1cmRheSwgU2VwdGVtYmVyIDEyLCAy
MDIwIDM6NTMgQU08YnI+PGI+VG86PC9iPiBBbG9rIFByaXlhZGFyc2hpICZsdDthcHJpeWFk
YXJzaGlAZW5waGFzZWVuZXJneS5jb20mZ3Q7PGJyPjxiPlN1YmplY3Q6PC9iPiBJbnZvaWNl
IG5vOi0gMzA3MDAyIFBPIE5vOi0gMjAyNjQyNSBOZWVkcyBBcHByb3ZhbDxvOnA+PC9vOnA+
PC9zcGFuPjwvcD48L2Rpdj48L2Rpdj48cCBjbGFzcz1Nc29Ob3JtYWw+PG86cD4mbmJzcDs8
L286cD48L3A+PHAgY2xhc3M9TXNvTm9ybWFsIHN0eWxlPSdtYXJnaW4tYm90dG9tOjEyLjBw
dCc+SGksIDxicj48YnI+UGxlYXNlIHJldmlldyB0aGUgYXR0YWNoZWQgaW52b2ljZSBhbmQg
cHJvdmlkZSB5b3VyIGVtYWlsIGFwcHJvdmFsIGZvciBwcm9jZXNzaW5nIGlmIHN1Y2ggc2Vy
dmljZXMgaGF2ZSBiZWVuIHJlY2VpdmVkIGFnYWluc3QgdGhpcyBpbnZvaWNlLiA8YnI+PGJy
PkFsc28sIGtpbmRseSBzaGFyZSBieSBlbWFpbCB0aGUgUE8gbnVtYmVyIHRvIG1hdGNoIHRo
ZSBpbnZvaWNlIHRvLiBUaGUgQVAgdGVhbSBpcyB1bmFibGUgdG8gcGF5IHRoZSB2ZW5kb3Ig
d2l0aG91dCBtYXRjaGluZyB0byBhIFBPIGluIE9yYWNsZS4gPGJyPkludm9pY2UgZGV0YWls
czo8bzpwPjwvbzpwPjwvcD48dGFibGUgY2xhc3M9TXNvTm9ybWFsVGFibGUgYm9yZGVyPTEg
Y2VsbHNwYWNpbmc9MCBjZWxscGFkZGluZz0wIHdpZHRoPTQ1MCBzdHlsZT0nd2lkdGg6MzM3
LjVwdDttYXJnaW4tbGVmdDozNy41cHQnPjx0cj48dGQgc3R5bGU9J2JhY2tncm91bmQ6bGln
aHRibHVlO3BhZGRpbmc6Ljc1cHQgLjc1cHQgLjc1cHQgLjc1cHQnPjxwIGNsYXNzPU1zb05v
cm1hbCBhbGlnbj1jZW50ZXIgc3R5bGU9J3RleHQtYWxpZ246Y2VudGVyJz48Yj5JbnZvaWNl
IERhdGU8bzpwPjwvbzpwPjwvYj48L3A+PC90ZD48dGQgc3R5bGU9J2JhY2tncm91bmQ6bGln
aHRibHVlO3BhZGRpbmc6Ljc1cHQgLjc1cHQgLjc1cHQgLjc1cHQnPjxwIGNsYXNzPU1zb05v
cm1hbCBhbGlnbj1jZW50ZXIgc3R5bGU9J3RleHQtYWxpZ246Y2VudGVyJz48Yj5JbnZvaWNl
IE51bWJlcjxvOnA+PC9vOnA+PC9iPjwvcD48L3RkPjx0ZCBzdHlsZT0nYmFja2dyb3VuZDps
aWdodGJsdWU7cGFkZGluZzouNzVwdCAuNzVwdCAuNzVwdCAuNzVwdCc+PHAgY2xhc3M9TXNv
Tm9ybWFsIGFsaWduPWNlbnRlciBzdHlsZT0ndGV4dC1hbGlnbjpjZW50ZXInPjxiPlZlbmRv
cjxvOnA+PC9vOnA+PC9iPjwvcD48L3RkPjx0ZCBzdHlsZT0nYmFja2dyb3VuZDpsaWdodGJs
dWU7cGFkZGluZzouNzVwdCAuNzVwdCAuNzVwdCAuNzVwdCc+PHAgY2xhc3M9TXNvTm9ybWFs
IGFsaWduPWNlbnRlciBzdHlsZT0ndGV4dC1hbGlnbjpjZW50ZXInPjxiPkFtb3VudDxvOnA+
PC9vOnA+PC9iPjwvcD48L3RkPjx0ZCBzdHlsZT0nYmFja2dyb3VuZDpsaWdodGJsdWU7cGFk
ZGluZzouNzVwdCAuNzVwdCAuNzVwdCAuNzVwdCc+PHAgY2xhc3M9TXNvTm9ybWFsIGFsaWdu
PWNlbnRlciBzdHlsZT0ndGV4dC1hbGlnbjpjZW50ZXInPjxiPlBPIE51bWJlcjxvOnA+PC9v
OnA+PC9iPjwvcD48L3RkPjwvdHI+PHRyPjx0ZCBzdHlsZT0ncGFkZGluZzouNzVwdCAuNzVw
dCAuNzVwdCAuNzVwdCc+PHAgY2xhc3M9TXNvTm9ybWFsPjA4LzA1LzIwMjAgMDA6MDA6MDA8
bzpwPjwvbzpwPjwvcD48L3RkPjx0ZCBzdHlsZT0ncGFkZGluZzouNzVwdCAuNzVwdCAuNzVw
dCAuNzVwdCc+PHAgY2xhc3M9TXNvTm9ybWFsPjMwNzAwMjxvOnA+PC9vOnA+PC9wPjwvdGQ+
PHRkIHN0eWxlPSdwYWRkaW5nOi43NXB0IC43NXB0IC43NXB0IC43NXB0Jz48cCBjbGFzcz1N
c29Ob3JtYWw+Q0xFQVJQQVRIIFdPUktGT1JDRSBNQU5BR0VNRU5UPG86cD48L286cD48L3A+
PC90ZD48dGQgc3R5bGU9J3BhZGRpbmc6Ljc1cHQgLjc1cHQgLjc1cHQgLjc1cHQnPjxwIGNs
YXNzPU1zb05vcm1hbD4xNTkxLjY1PG86cD48L286cD48L3A+PC90ZD48dGQgc3R5bGU9J3Bh
ZGRpbmc6Ljc1cHQgLjc1cHQgLjc1cHQgLjc1cHQnPjxwIGNsYXNzPU1zb05vcm1hbD4yMDI2
NDI1PG86cD48L286cD48L3A+PC90ZD48L3RyPjwvdGFibGU+PHAgY2xhc3M9TXNvTm9ybWFs
Pjxicj48YnI+UmVnYXJkcyw8YnI+QVAgVGVhbSA8bzpwPjwvbzpwPjwvcD48L2Rpdj48L2Jv
ZHk+PC9odG1sPg==

--=-0bwXtqomHyVrDAYGM2Zttg==--
