Uid: =?us-ascii?q?000000002D981BCA7B16584E89D34CA3742853680700BA72AEFAFEEE06458?=
 =?us-ascii?q?610A5DE8BDDBB9000000000010C0000BA72AEFAFEEE06458610A5DE8BDDBB?=
 =?us-ascii?q?9000001068E1EC0000?=
Date: 09/18/2020 07:05:03
DateCreated: 09/18/2020 07:05:05
DateRecieved: 09/18/2020 07:05:05
HtmlBody: <html xmlns:v="urn:schemas-microsoft-com:vml"
 xmlns:o="urn:schemas-microsoft-com:office:office"
 xmlns:w="urn:schemas-microsoft-com:office:word"
 xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
 xmlns="http://www.w3.org/TR/REC-html40"><head><meta name=Generator
 content="Microsoft Word 15 (filtered medium)"><style><!--/* Font Definitions
 */@font-face	{font-family:"Cambria Math";	panose-1:2 4 5 3 5 4 6 3 2
 4;}@font-face	{font-family:Calibri;	panose-1:2 15 5 2 2 2 4 3 2 4;}/* Style
 Definitions */p.MsoNormal, li.MsoNormal, div.MsoNormal	{margin:0in;
	font-size:11.0pt;	font-family:"Calibri",sans-serif;
	color:#1F497D;}.MsoChpDefault	{mso-style-type:export-only;
	font-size:10.0pt;}@page WordSection1	{size:8.5in 11.0in;	margin:1.0in 1.0in
 1.0in 1.0in;}div.WordSection1	{page:WordSection1;}--></style><!--[if gte mso
 9]><xml><o:shapedefaults v:ext="edit" spidmax="1026"
 /></xml><![endif]--><!--[if gte mso 9]><xml><o:shapelayout
 v:ext="edit"><o:idmap v:ext="edit" data="1"
 /></o:shapelayout></xml><![endif]--></head><body lang=EN-US link="#0563C1"
 vlink="#954F72"><div class=WordSection1><p class=MsoNormal><span
 style='color:windowtext'><o:p>&nbsp;</o:p></span></p><p class=MsoNormal><span
 style='color:windowtext'>Approved<o:p></o:p></span></p><div><div
 style='border:none;border-top:solid #E1E1E1 1.0pt;padding:3.0pt 0in 0in
 0in'><p class=MsoNormal><b><span
 style='color:windowtext'>From:</span></b><span style='color:windowtext'> Alok
 Priyadarshi &lt;apriyadarshi@enphaseenergy.com&gt; <br><b>Sent:</b> Friday,
 September 18, 2020 7:34 PM<br><b>To:</b> Thippeswamy
 &lt;thippeswamy@enphaseenergy.com&gt;<br><b>Subject:</b> Invoice no:- 306995
 PO No:- 2023451 Needs Approval<o:p></o:p></span></p></div></div><p
 class=MsoNormal><o:p>&nbsp;</o:p></p><p class=MsoNormal
 style='margin-bottom:12.0pt'>Hi, <br><br>Please review the attached invoice
 and provide your email approval for processing if such services have been
 received against this invoice. <br><br>Also, kindly share by email the PO
 number to match the invoice to. The AP team is unable to pay the vendor
 without matching to a PO in Oracle. <br>Invoice details:<o:p></o:p></p><table
 class=MsoNormalTable border=1 cellspacing=0 cellpadding=0 width=450
 style='width:337.5pt;margin-left:37.5pt'><tr><td
 style='background:lightblue;padding:.6pt .6pt .6pt .6pt'><p class=MsoNormal
 align=center style='text-align:center'><b>Invoice
 Date<o:p></o:p></b></p></td><td style='background:lightblue;padding:.6pt .6pt
 .6pt .6pt'><p class=MsoNormal align=center
 style='text-align:center'><b>Invoice Number<o:p></o:p></b></p></td><td
 style='background:lightblue;padding:.6pt .6pt .6pt .6pt'><p class=MsoNormal
 align=center style='text-align:center'><b>Vendor<o:p></o:p></b></p></td><td
 style='background:lightblue;padding:.6pt .6pt .6pt .6pt'><p class=MsoNormal
 align=center style='text-align:center'><b>Amount<o:p></o:p></b></p></td><td
 style='background:lightblue;padding:.6pt .6pt .6pt .6pt'><p class=MsoNormal
 align=center style='text-align:center'><b>PO
 Number<o:p></o:p></b></p></td></tr><tr><td style='padding:.6pt .6pt .6pt
 .6pt'><p class=MsoNormal>08/05/2020 00:00:00<o:p></o:p></p></td><td
 style='padding:.6pt .6pt .6pt .6pt'><p
 class=MsoNormal>306995<o:p></o:p></p></td><td style='padding:.6pt .6pt .6pt
 .6pt'><p class=MsoNormal>CLEARPATH WORKFORCE
 MANAGEMENT<o:p></o:p></p></td><td style='padding:.6pt .6pt .6pt .6pt'><p
 class=MsoNormal>3722.66<o:p></o:p></p></td><td style='padding:.6pt .6pt .6pt
 .6pt'><p class=MsoNormal>2023451<o:p></o:p></p></td></tr></table><p
 class=MsoNormal><br><br>Regards,<br>AP Team
 <o:p></o:p></p></div></body></html>
PlainText: ApprovedFrom: Alok Priyadarshi <apriyadarshi@enphaseenergy.com>
 Sent: Friday, September 18, 2020 7:34 PMTo: Thippeswamy
 <thippeswamy@enphaseenergy.com>Subject: Invoice no:- 306995 PO No:- 2023451
 Needs Approval Hi, Please review the attached invoice and provide your email
 approval for processing if such services have been received against this
 invoice. Also, kindly share by email the PO number to match the invoice to.
 The AP team is unable to pay the vendor without matching to a PO in Oracle.
 Invoice details:Invoice DateInvoice NumberVendorAmountPO Number08/05/2020
 00:00:00306995CLEARPATH WORKFORCE MANAGEMENT3722.662023451Regards,AP Team
Size: 49081
Sender: Thippeswamy <thippeswamy@enphaseenergy.com>
From: Thippeswamy <thippeswamy@enphaseenergy.com>
To: Alok Priyadarshi <apriyadarshi@enphaseenergy.com>
Subject: RE: Invoice no:- 306995  PO No:- 2023451   Needs Approval
MIME-Version: 1.0
Content-Type: multipart/alternative; boundary="=-o00yHrSK0Knqt/BgL9fqeA=="

--=-o00yHrSK0Knqt/BgL9fqeA==
Content-Type: text/plain; charset=us-ascii

 

Approved

From: Alok Priyadarshi <apriyadarshi@enphaseenergy.com> 
Sent: Friday, September 18, 2020 7:34 PM
To: Thippeswamy <thippeswamy@enphaseenergy.com>
Subject: Invoice no:- 306995 PO No:- 2023451 Needs Approval

 

Hi, 

Please review the attached invoice and provide your email approval for processing if such services have been received against this invoice. 

Also, kindly share by email the PO number to match the invoice to. The AP team is unable to pay the vendor without matching to a PO in Oracle. 
Invoice details:

Invoice Date

Invoice Number

Vendor

Amount

PO Number

08/05/2020 00:00:00

306995

CLEARPATH WORKFORCE MANAGEMENT

3722.66

2023451



Regards,
AP Team 

--=-o00yHrSK0Knqt/BgL9fqeA==
Content-Type: text/html
Content-Transfer-Encoding: base64
Content-Id: <bc18309b-2308-4967-920a-7d32b6556949>

PGh0bWwgeG1sbnM6dj0idXJuOnNjaGVtYXMtbWljcm9zb2Z0LWNvbTp2bWwiIHhtbG5zOm89
InVybjpzY2hlbWFzLW1pY3Jvc29mdC1jb206b2ZmaWNlOm9mZmljZSIgeG1sbnM6dz0idXJu
OnNjaGVtYXMtbWljcm9zb2Z0LWNvbTpvZmZpY2U6d29yZCIgeG1sbnM6bT0iaHR0cDovL3Nj
aGVtYXMubWljcm9zb2Z0LmNvbS9vZmZpY2UvMjAwNC8xMi9vbW1sIiB4bWxucz0iaHR0cDov
L3d3dy53My5vcmcvVFIvUkVDLWh0bWw0MCI+PGhlYWQ+PG1ldGEgbmFtZT1HZW5lcmF0b3Ig
Y29udGVudD0iTWljcm9zb2Z0IFdvcmQgMTUgKGZpbHRlcmVkIG1lZGl1bSkiPjxzdHlsZT48
IS0tDQovKiBGb250IERlZmluaXRpb25zICovDQpAZm9udC1mYWNlDQoJe2ZvbnQtZmFtaWx5
OiJDYW1icmlhIE1hdGgiOw0KCXBhbm9zZS0xOjIgNCA1IDMgNSA0IDYgMyAyIDQ7fQ0KQGZv
bnQtZmFjZQ0KCXtmb250LWZhbWlseTpDYWxpYnJpOw0KCXBhbm9zZS0xOjIgMTUgNSAyIDIg
MiA0IDMgMiA0O30NCi8qIFN0eWxlIERlZmluaXRpb25zICovDQpwLk1zb05vcm1hbCwgbGku
TXNvTm9ybWFsLCBkaXYuTXNvTm9ybWFsDQoJe21hcmdpbjowaW47DQoJZm9udC1zaXplOjEx
LjBwdDsNCglmb250LWZhbWlseToiQ2FsaWJyaSIsc2Fucy1zZXJpZjsNCgljb2xvcjojMUY0
OTdEO30NCi5Nc29DaHBEZWZhdWx0DQoJe21zby1zdHlsZS10eXBlOmV4cG9ydC1vbmx5Ow0K
CWZvbnQtc2l6ZToxMC4wcHQ7fQ0KQHBhZ2UgV29yZFNlY3Rpb24xDQoJe3NpemU6OC41aW4g
MTEuMGluOw0KCW1hcmdpbjoxLjBpbiAxLjBpbiAxLjBpbiAxLjBpbjt9DQpkaXYuV29yZFNl
Y3Rpb24xDQoJe3BhZ2U6V29yZFNlY3Rpb24xO30NCi0tPjwvc3R5bGU+PCEtLVtpZiBndGUg
bXNvIDldPjx4bWw+DQo8bzpzaGFwZWRlZmF1bHRzIHY6ZXh0PSJlZGl0IiBzcGlkbWF4PSIx
MDI2IiAvPg0KPC94bWw+PCFbZW5kaWZdLS0+PCEtLVtpZiBndGUgbXNvIDldPjx4bWw+DQo8
bzpzaGFwZWxheW91dCB2OmV4dD0iZWRpdCI+DQo8bzppZG1hcCB2OmV4dD0iZWRpdCIgZGF0
YT0iMSIgLz4NCjwvbzpzaGFwZWxheW91dD48L3htbD48IVtlbmRpZl0tLT48L2hlYWQ+PGJv
ZHkgbGFuZz1FTi1VUyBsaW5rPSIjMDU2M0MxIiB2bGluaz0iIzk1NEY3MiI+PGRpdiBjbGFz
cz1Xb3JkU2VjdGlvbjE+PHAgY2xhc3M9TXNvTm9ybWFsPjxzcGFuIHN0eWxlPSdjb2xvcjp3
aW5kb3d0ZXh0Jz48bzpwPiZuYnNwOzwvbzpwPjwvc3Bhbj48L3A+PHAgY2xhc3M9TXNvTm9y
bWFsPjxzcGFuIHN0eWxlPSdjb2xvcjp3aW5kb3d0ZXh0Jz5BcHByb3ZlZDxvOnA+PC9vOnA+
PC9zcGFuPjwvcD48ZGl2PjxkaXYgc3R5bGU9J2JvcmRlcjpub25lO2JvcmRlci10b3A6c29s
aWQgI0UxRTFFMSAxLjBwdDtwYWRkaW5nOjMuMHB0IDBpbiAwaW4gMGluJz48cCBjbGFzcz1N
c29Ob3JtYWw+PGI+PHNwYW4gc3R5bGU9J2NvbG9yOndpbmRvd3RleHQnPkZyb206PC9zcGFu
PjwvYj48c3BhbiBzdHlsZT0nY29sb3I6d2luZG93dGV4dCc+IEFsb2sgUHJpeWFkYXJzaGkg
Jmx0O2Fwcml5YWRhcnNoaUBlbnBoYXNlZW5lcmd5LmNvbSZndDsgPGJyPjxiPlNlbnQ6PC9i
PiBGcmlkYXksIFNlcHRlbWJlciAxOCwgMjAyMCA3OjM0IFBNPGJyPjxiPlRvOjwvYj4gVGhp
cHBlc3dhbXkgJmx0O3RoaXBwZXN3YW15QGVucGhhc2VlbmVyZ3kuY29tJmd0Ozxicj48Yj5T
dWJqZWN0OjwvYj4gSW52b2ljZSBubzotIDMwNjk5NSBQTyBObzotIDIwMjM0NTEgTmVlZHMg
QXBwcm92YWw8bzpwPjwvbzpwPjwvc3Bhbj48L3A+PC9kaXY+PC9kaXY+PHAgY2xhc3M9TXNv
Tm9ybWFsPjxvOnA+Jm5ic3A7PC9vOnA+PC9wPjxwIGNsYXNzPU1zb05vcm1hbCBzdHlsZT0n
bWFyZ2luLWJvdHRvbToxMi4wcHQnPkhpLCA8YnI+PGJyPlBsZWFzZSByZXZpZXcgdGhlIGF0
dGFjaGVkIGludm9pY2UgYW5kIHByb3ZpZGUgeW91ciBlbWFpbCBhcHByb3ZhbCBmb3IgcHJv
Y2Vzc2luZyBpZiBzdWNoIHNlcnZpY2VzIGhhdmUgYmVlbiByZWNlaXZlZCBhZ2FpbnN0IHRo
aXMgaW52b2ljZS4gPGJyPjxicj5BbHNvLCBraW5kbHkgc2hhcmUgYnkgZW1haWwgdGhlIFBP
IG51bWJlciB0byBtYXRjaCB0aGUgaW52b2ljZSB0by4gVGhlIEFQIHRlYW0gaXMgdW5hYmxl
IHRvIHBheSB0aGUgdmVuZG9yIHdpdGhvdXQgbWF0Y2hpbmcgdG8gYSBQTyBpbiBPcmFjbGUu
IDxicj5JbnZvaWNlIGRldGFpbHM6PG86cD48L286cD48L3A+PHRhYmxlIGNsYXNzPU1zb05v
cm1hbFRhYmxlIGJvcmRlcj0xIGNlbGxzcGFjaW5nPTAgY2VsbHBhZGRpbmc9MCB3aWR0aD00
NTAgc3R5bGU9J3dpZHRoOjMzNy41cHQ7bWFyZ2luLWxlZnQ6MzcuNXB0Jz48dHI+PHRkIHN0
eWxlPSdiYWNrZ3JvdW5kOmxpZ2h0Ymx1ZTtwYWRkaW5nOi42cHQgLjZwdCAuNnB0IC42cHQn
PjxwIGNsYXNzPU1zb05vcm1hbCBhbGlnbj1jZW50ZXIgc3R5bGU9J3RleHQtYWxpZ246Y2Vu
dGVyJz48Yj5JbnZvaWNlIERhdGU8bzpwPjwvbzpwPjwvYj48L3A+PC90ZD48dGQgc3R5bGU9
J2JhY2tncm91bmQ6bGlnaHRibHVlO3BhZGRpbmc6LjZwdCAuNnB0IC42cHQgLjZwdCc+PHAg
Y2xhc3M9TXNvTm9ybWFsIGFsaWduPWNlbnRlciBzdHlsZT0ndGV4dC1hbGlnbjpjZW50ZXIn
PjxiPkludm9pY2UgTnVtYmVyPG86cD48L286cD48L2I+PC9wPjwvdGQ+PHRkIHN0eWxlPSdi
YWNrZ3JvdW5kOmxpZ2h0Ymx1ZTtwYWRkaW5nOi42cHQgLjZwdCAuNnB0IC42cHQnPjxwIGNs
YXNzPU1zb05vcm1hbCBhbGlnbj1jZW50ZXIgc3R5bGU9J3RleHQtYWxpZ246Y2VudGVyJz48
Yj5WZW5kb3I8bzpwPjwvbzpwPjwvYj48L3A+PC90ZD48dGQgc3R5bGU9J2JhY2tncm91bmQ6
bGlnaHRibHVlO3BhZGRpbmc6LjZwdCAuNnB0IC42cHQgLjZwdCc+PHAgY2xhc3M9TXNvTm9y
bWFsIGFsaWduPWNlbnRlciBzdHlsZT0ndGV4dC1hbGlnbjpjZW50ZXInPjxiPkFtb3VudDxv
OnA+PC9vOnA+PC9iPjwvcD48L3RkPjx0ZCBzdHlsZT0nYmFja2dyb3VuZDpsaWdodGJsdWU7
cGFkZGluZzouNnB0IC42cHQgLjZwdCAuNnB0Jz48cCBjbGFzcz1Nc29Ob3JtYWwgYWxpZ249
Y2VudGVyIHN0eWxlPSd0ZXh0LWFsaWduOmNlbnRlcic+PGI+UE8gTnVtYmVyPG86cD48L286
cD48L2I+PC9wPjwvdGQ+PC90cj48dHI+PHRkIHN0eWxlPSdwYWRkaW5nOi42cHQgLjZwdCAu
NnB0IC42cHQnPjxwIGNsYXNzPU1zb05vcm1hbD4wOC8wNS8yMDIwIDAwOjAwOjAwPG86cD48
L286cD48L3A+PC90ZD48dGQgc3R5bGU9J3BhZGRpbmc6LjZwdCAuNnB0IC42cHQgLjZwdCc+
PHAgY2xhc3M9TXNvTm9ybWFsPjMwNjk5NTxvOnA+PC9vOnA+PC9wPjwvdGQ+PHRkIHN0eWxl
PSdwYWRkaW5nOi42cHQgLjZwdCAuNnB0IC42cHQnPjxwIGNsYXNzPU1zb05vcm1hbD5DTEVB
UlBBVEggV09SS0ZPUkNFIE1BTkFHRU1FTlQ8bzpwPjwvbzpwPjwvcD48L3RkPjx0ZCBzdHls
ZT0ncGFkZGluZzouNnB0IC42cHQgLjZwdCAuNnB0Jz48cCBjbGFzcz1Nc29Ob3JtYWw+Mzcy
Mi42NjxvOnA+PC9vOnA+PC9wPjwvdGQ+PHRkIHN0eWxlPSdwYWRkaW5nOi42cHQgLjZwdCAu
NnB0IC42cHQnPjxwIGNsYXNzPU1zb05vcm1hbD4yMDIzNDUxPG86cD48L286cD48L3A+PC90
ZD48L3RyPjwvdGFibGU+PHAgY2xhc3M9TXNvTm9ybWFsPjxicj48YnI+UmVnYXJkcyw8YnI+
QVAgVGVhbSA8bzpwPjwvbzpwPjwvcD48L2Rpdj48L2JvZHk+PC9odG1sPg==

--=-o00yHrSK0Knqt/BgL9fqeA==--
